name: SNBizz
description: Sujan nakarmi business application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.5+12

environment:
 sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker:
  splashscreen:
  flutter_screenutil: ^0.5.2
  http: ^0.12.0+1
  connectivity: ^0.4.2
  flutter_secure_storage: ^3.3.1
  file_picker: 
  flutter_datetime_picker: 1.2.5
  angles: ^1.2.1
  dio: 
  multi_image_picker: 
  carousel_pro: ^1.0.0
  datetime_picker_formfield: ^0.4.3
  firebase_messaging: ^4.0.0+4
  flutter_local_notifications: ^0.8.4
  shared_preferences: ^0.5.4+5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_money_formatter: ^0.8.3
  basic_utils: ^2.3.0
  rxdart: 
  intl: ^0.15.7
  uuid: ^2.0.2
  date_format:
  url_launcher: ^4.2.0+3
  pull_to_refresh: ^1.4.5
  carousel_slider: ^1.3.1
  flutter_image_compress: ^0.6.3
  flutter_webview_plugin: ^0.3.8
  flutter_rounded_progress_bar: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  

#For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec 

# The following section is specific to Flutter.
flutter:



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/whatsapp.png
   - assets/facebook.png
   - assets/docicon.png
   - assets/file.png
   - assets/camera.png
   - assets/pdf.png
   - assets/setting.png
   - assets/contact.png
   - assets/logout.png
   - assets/new_meeting.png
   - assets/time.png
   - assets/snbizlogo.png
   - assets/about.png
   - assets/snbiznotification.png
   - assets/snbizrunning-web.png
   - assets/acceptedtick-web.png
   - assets/snbizmeetings.png
   - assets/snbiztasks.png
   - assets/snbizmeeting.png
   - assets/snbizinvoice.png
   - assets/snbizuploads.png
   - assets/snbizcircledocument.png
   - assets/notification.png
   - assets/snbizinstantupload.png
   - assets/snbizvaticon.png
   - assets/snbizdeclinedicon.png
   - assets/snbizscheduled.png
   - assets/snbizspostponed.png
   - assets/snbizsfiles-web.png
   - assets/snbizcancel-web.png
   - assets/new-dashboard.png
   - assets/legals.png
   - assets/registration-web.png
   - assets/expense-web.png
   - assets/income-web.png
   - assets/profit-web.png
   - assets/bannerpicturehome.jpg
   - assets/mp4-icon.jpg
   - assets/transparent.png
   - assets/intro1.png
   - assets/intro2.png
   - assets/intro3.png
   - assets/intro4.png
   - assets/snbiztasks_notification.png
   - assets/snbizcircledocument_notification.png
   - assets/vaticon.png
   - assets/docnew.png
   - assets/foldernewicon.png
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        #uses-material-design: true
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

